# Generated by Django 4.2.3 on 2023-08-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_studycase_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='diffexpranalysisdata',
            name='gene_id',
            field=models.CharField(default='hnjmk', max_length=50),
            preserve_default=False,
        ),
    ]
